[package]
name = "devdocs-bindings"
version = "0.1.0"
edition = "2021"

[dependencies]
devdocs-core = { path = "../devdocs-core" }
devdocs-middleware = { path = "../devdocs-middleware" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
