[target.x86_64-unknown-linux-gnu]
linker = "gcc"

[build]
jobs = 4

[net]
git-fetch-with-cli = true

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
debug = 2
incremental = true
